allowBuilds:
  '@parcel/watcher': set this to true or false
  '@sentry/cli': set this to true or false
  '@serialport/bindings-cpp': set this to true or false
  '@tabby-gang/windows-blurbehind': set this to true or false
  '@tabby-gang/windows-process-tree': set this to true or false
  '@vaadin/vaadin-usage-statistics': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  electron: set this to true or false
  electron-winstaller: set this to true or false
  fontmanager-redux: set this to true or false
  glasstron: set this to true or false
  keytar: set this to true or false
  native-process-working-directory: set this to true or false
  node-pty: set this to true or false
  tabby-ssh: set this to true or false
  unrs-resolver: set this to true or false
  windows-native-registry: set this to true or false
